name: Publish test site
on:
  push:
    branches:
       - kun-dev

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # fetch all commits/branches

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.7'
          architecture: 'x64'

      - name: apt install
        run: |
          sudo apt update -y
          sudo apt install -y $(cat pkglist.txt)
      - name: Install dependencies  
        run: |
          pip install --upgrade pip
          pip install -r ./requirements.txt
      - name: Git Config  
        run: git config user.name whitewum && git config user.email min.wu@vesoft.com

      - name: mike list delete
        run: |
          mike list
      - name: Mike Deploy 2.0.1
        run: |
          mike deploy 2.0.1 -p
          mike set-default 2.0.1 -p --rebase
          mike list  
      - name: show git branch
        run: | 
          git branch
          git checkout gh-pages
      - name: Compress
        run: |
           tar -czf nebula-docs.tar.gz * --exclude=*.tar.gz
      - name: Transfer
        # uses: garygrossgarten/github-action-scp@release
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.TEST_HOST }}
          username: ${{ secrets.TEST_USER_NAME }}
          password: ${{ secrets.TEST_PASSWORD }}
          port: ${{ secrets.TEST_PORT }}
          source: nebula-docs.tar.gz
          target: /usr/www

      - name: UnCompress
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.TEST_HOST }}
          username: ${{ secrets.TEST_USER_NAME }}
          password: ${{ secrets.TEST_PASSWORD }}
          port: ${{ secrets.TEST_PORT }}
          script: |
            mkdir -p /usr/www/nebula-docs/
            tar -xzf /usr/www/nebula-docs.tar.gz -C /usr/www/nebula-docs/
